#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # onedark: 暗色主题字体绿色, grevbox：默认主题 molokai：以前终端的颜色 jellybeans: 背景颜色纯黑，字体绿色.但是图标不喜欢
    # one:背景颜色纯黑，字体绿色，图标不错 # nord 纯黑字体神绿 背景图标白 #  hybrid 暗黑主题，图标白色 # material 不喜欢 # SpaceVim骚
    colorscheme = "hybrid_reverse"
    colorscheme_bg = "dark" # dark
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # 自定义配置函数
    bootstrap_before = "myspacevim#before"
    # bootstrap_after  = "myspacevim#after"
    # 文件树插件可选值包括：
    # - vimfiler （默认）
    # - nerdtree
    # - defx
    filemanager = "nerdtree"

    # 选择检测语法工具
    enable_neomake = false # 这个检测语法，每次保存都会在文件目录生成编译文件夹，这点很烦人
    enable_ale = true
    lint_on_the_fly = true #启用实时语法检查
    vim_help_language = "cn" # 设置中文文档插件，需要安装chinese插件
    layer_lang_java_formatter = "~/.SpaceVim.d/path/to/google-java-format-1.7-all-deps.jar" # 重要，java格式化必须设置 为了使 format 模块支持 Java 文件
    


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
# auto-completion-return-key-behavior = "complete"
# auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

# 配置java模块
[[layers]]
name = "lang#java"

# 主题插件
[[layers]]
name = "colorscheme"

# 超级搜索
[[layers]]
name = "ctrlp"
# 快捷键
# <Leader> f <Space>  模糊查找快捷键，并执行该快捷键
# <Leader> f e  模糊搜索寄存器
# <Leader> f h  模糊搜索 history/yank
# <Leader> f j  模糊搜索 jump, change
# <Leader> f l  模糊搜索 location list
# <Leader> f m  模糊搜索 output messages
# <Leader> f o  模糊搜索函数列表
# <Leader> f q  模糊搜索 quickfix list
# <Leader> f r  重置上次搜索窗口

# 代码折叠 太卡了。注释了
# [[custom_plugins]]
# name = "tmhedberg/SimpylFold"
# merged = false

# 代码格式化
[[layers]]
name = "format"

# 语法检查模块
# [[layers]]
# name = "checkers"
# show_cursor_error = false # 关闭光标的下一行显示当前行错误的详细信息

# 中文帮助文档
# [[layers]]
# name = "chinese"

# 模糊搜索快速调到当前文件中的某个函数
[[layers]]
name = "denite"


# 语言服务器模块
[[layers]]
name = "lsp"
filetypes = [
  "java"
]

[layers.override_cmd]
java = [
   "java",
   "-Declipse.application=org.eclipse.jdt.ls.core.id1",
   "-Dosgi.bundles.defaultStartLevel=4",
   "-Declipse.product=org.eclipse.jdt.ls.core.product",
   "-Dlog.protocol=true",
   "-Dlog.level=NONE",
   "-noverify",
   "-Xmx1G",
   "-jar",
# "//dev//.SpaceVim.d//jdt-language-server-latest//plugins//org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar",
   "~/.SpaceVim.d/jdt-language-server-latest/plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar",
   "-configuration",
   "~/.SpaceVim.d/jdt-language-server-latest/config_linux",
   "-data",
   "~/.cache/javalsp",
   ]
